In [5]:
%pip install torch

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch


# How to train our first neural network with PyTorch

## How to execute a step forward

In [3]:
# - Load from list
import torch
import numpy as np
import torch.nn as nn

# lst = [ [1,2,3] , [4,5,6] ]
# tensor = torch.tensor(lst)

# # - Load from NumPy array
# np_array = np.array(array)
# np_tensor = torch.from_numpy(nop_array)

### Binary classification: forward pass

In [6]:
# Create input data of shape 5x6
input_data = torch.tensor(
    [[-0.4421, 1.5207, 2.0607, -0.3647, 0.4691, 0.0946],
    [-0.9155, -0.0475, -1.3645, 0.6336, -1.9520, -0.3398],
    [0.7406, 1.6763, -0.8511, 0.2432, 0.1123, -0.0633],
    [-1.6630, -0.0718, -0.1285, 0.5396, -0.0288, -0.8622],
    [-0.7413, 1.7920, -0.0883, -0.6685, 0.4745, -0.4245]])

# Create binary classification model
model = nn.Sequential(
    nn.Linear(6,4), # First Linear layer
    nn.Linear(4,1), # First Linear layer
    nn.Sigmoid()   # Sigmoid activation function
)

"""
    - O primeiro argumento da primeira camada corresponde ao
    número de neurônios em nossos dados de amostra.
    - O primeiro argumento da segunda camada corresponde à
    dimensão de saída da primeira camada.
"""

# Pass input data through model to obtain the output
output = model(input_data)
output

tensor([[0.5774],
        [0.4423],
        [0.5451],
        [0.4837],
        [0.6442]], grad_fn=<SigmoidBackward0>)

This output will not be meaningful until we use backpropagation to update the weights and biases of the layers.

### Multi-class classification: forward pass

Digamos que estavmos prevendo três classes: mamífero, ave ou répitil.

Especificamos que nosso modelo tem três classes, definindo esse valor como a dimensão de saída da última camada linear.

In [9]:
# Specify model has three classes
n_classes = 3

# Create multiclasses classification model
model = nn.Sequential(
    nn.Linear(6, 4),            # First Linear layer
    nn.Linear(4, n_classes),    # Second Linear layer
    nn.Softmax(dim=-1)          # Softmax activation, "-1" indica que as cinco amostras têm a mesma dimensão que a saída da última camada linear
)

# Pass input data through model
output = model(input_data)
print(output.shape)
output

torch.Size([5, 3])


tensor([[0.2638, 0.3866, 0.3496],
        [0.3017, 0.2853, 0.4130],
        [0.4274, 0.2649, 0.3077],
        [0.2959, 0.3346, 0.3695],
        [0.4115, 0.2709, 0.3177]], grad_fn=<SoftmaxBackward0>)

### Regression: forward pass

Previsão de valores numéricos contínuos.

Digamos que usamos os mesmos dados sobre cinco animais, mas desta vez estamos prevendo pesos de animais com base em sua propriedades.

A diferença é que não há função de ativação no final, e a última dimensão da última camada linear retorna uma saída com um recurso.

In [10]:
# Create regression model
model = nn.Sequential(
    nn.Linear(6,4),     # First Linear layer
    nn.Linear(4,1),     # First Linear layer
)

# Pass input data through model
output = model(input_data)

print(output)

tensor([[-0.3416],
        [-0.2219],
        [-0.2909],
        [-0.1067],
        [-0.1900]], grad_fn=<AddmmBackward0>)


As dimensões de saída são 5x1: cinco valores contínuos, um para cada linha. 

## Como criar um classificador binário no PyTorch